---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: basic-sanity-check-jsz
spec:
  stepTemplate:
    volumeMounts:
      - name: project
        mountPath: /workspace/source/image
  params:
    - name: sourceImage
      description: the fully qualified image name
      default: quay.io/cvpops/test-index:v4.10
  steps:
    - name: clone-git-repo
      image: alpine/git
      script: "git clone https://github.com/dirgim/hacbs-conftest.git /project"
      volumeMounts:
        - name: project
          mountPath: /project
    - name: inspect-image
      image: quay.io/skopeo/stable:latest
      script: "skopeo inspect docker://$(inputs.params.sourceImage) > /project/image_inspect.json"
      volumeMounts:
        - name: project
          mountPath: /project
    - name: basic-sanity-checks-required-labels
      image: openpolicyagent/conftest
      args:
        - "test"
        - "image_inspect.json"
        - "--policy"
        - "/project/image/policy/required-labels.rego"
        - "--output=json"
      volumeMounts:
        - name: project
          mountPath: /project
    - name: basic-sanity-checks-deprecated-labels
      image: openpolicyagent/conftest
      args:
        - "test"
        - "image_inspect.json"
        - "--policy"
        - "/project/image/policy/deprecated-labels.rego"
        - "--output=json"
      volumeMounts:
        - name: project
          mountPath: /project
  volumes:
    - name: project
      emptyDir: {}
